endpoint:
  naver:
    news:
      rank: https://news.naver.com/main/ranking/popularDay.naver
  google:
    youtube:
      popular: https://www.googleapis.com/youtube/v3/videos

cron:
  expression:
    naverNewsRank: 0 0 * * * * # 매시 정각
    youtubePopular: 0 0 * * * * # 매시 정각
    keyword: 0 0 2 * * * # 매일 02시