server:
  port: 30010
spring:
  application:
    name: issueMoaBatch
  config:
    import: optional:configserver:http://61.102.114.235:8888
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
logging:
  level:
    root: info

eureka:
  client:
    enabled: false
    register-with-eureka: false  # Eureka 서버에 등록하지 않음
    fetch-registry: false        # 레지스트리를 가져오지 않음
